### ISSUE TITLE
Questions about UMI and Barcode Position

### ISSUE THREAD

**Issue by dumaatravaie** [paulranum11/SPLiT-Seq_demultiplexing#4] opened 2019-07-17 14:09 UTC
Hi,
Thank you for this good work.

I am testing your last version of SPLiT-Seq_demultiplexing0.1.1.
As, i understood from the SplitSeq Protocol, the Read1 and Read2 of fastq files are described as :

Read 1 (66 nt) = transcript
Read 2 (94 nt) = UMI + BC3 + spacer + BC2 +spacer + BC1
where the UMI starts at - 1nts, BC3- Starts at 11 nts, BC2- Starts at 48 nts, BC1- Starts at 86 nts

So, when i look at the results of  SPLiT-Seq_demultiplexing0.1.1 ( using small test fastq files downloaded along with this logiciel ) of merged fastq files, the UMI is always the first 10 nts of READ1 not first 10nts of READ2 !!! 

For example ( for this read 1 and read 2 ):

Read1:

@SRR6750041.1 1/1
CTGGANAAGTGAAATAATATAAATTTTTCCACTATTGAATAAAAGCAACTTAAATTTTCTAAGTCG
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEA<AAEEEEE<6

Read2:

@SRR6750041.1 1/2
NNTACTAAAGGCTAACGAGTGGCCGCTGTTTCGCATCGGCGTACGACTATTGAGGAATCCACGTGCTTGAGAGGCCAGAGCATTCGAACGCTTA
+
##AAAEEEEEEEEEEEEEE/6E/EE6/EAE<66666AEAAAE66<<</<<EEEEEEEEAAAAE666666AAE<<EEEEEEEE<AEAEEEEEEE/

SPLiT-Seq_demultiplexing0.1.1 produces the output as : 

@SRR6750041.1_AGCATTCGAACGCTTAATTGAGGAATCCAGCTAACGAGTGGCC_CTGGANAAGT 1/1
CTGGANAAGTGAAATAATATAAATTTTTCCACTATTGAATAAAAGCAACTTAAATTTTCTAAGTCG
+
AAAAA#EEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEA<AAEEEEE<6

Where in the header last characters _CTGGANAAGT  is the UMI, which is the first 10nts of READ1 not READ2 !!!!

So, Can you please tell me whether this is correct, or it is me who is wrong.

I hope i could explain you clearly.
Thank you in advance for your reply,
with best wishes,
Duma

**Comment by paulranum11** [comment] 2019-07-17 17:24
Hi Duma,

Thanks for spotting this, it was due to a bug I introduced in the last update where I revised the UMI extraction. I fixed it and pushed an update to the repository.  

Thanks,
- Paul

**Comment by dumaatravaie** [comment] 2019-07-17 19:20
Hi Paul,
             Thank you for your reply. Just one last question.

**Does SPLiT-Seq_demultiplexing0.1.1 searches for the Barcodes in specific positions in the reads of READ2** ?

 According to Splt-seq protocol, Barcode3 should start at position 11nts, Barcode2 at Position 48 nts and Barcodes1 at position 86nts in Read2. 

Thank you again in advance for your reply.
with best wishes
Duma

**Comment by paulranum11** [comment] 2019-07-17 19:56
Hi Duma,

Yes SPLiT-Seq_demultiplexing searches for the barcodes in read 2.  However, rather than use fixed barcode positions (11nts, 48nts, 86nts etc) SPLiT-Seq_demultiplexing uses searches for barcodes based on their sequence + a static flanking sequence.  See the Round1_barcodes_new5.txt, Round2_barcodes_new4.txt, Round3_barcodes_new4.txt barcode files as examples. Additionally the barcodes must be found in the correct order. By using this approach instead of fixed positions the demultiplexing process remains accurate even for sequences where the read starts in a slightly different position and reads containing insertions or deletions at non-barcode positions.

**Comment by dumaatravaie** [comment] 2019-07-18 07:11
Hi Paul,
                  Thank you for your reply. Now its clear. As , i am trying to demultiplex our Splitseq data ( 27 GB ) where the sequening did not work very well, because the reads of READ2 are 84nts in length ( Other then 94 nts defined by splitseq protocols ). So, we thought that there can't be Barcode1 in Read2 as the reads are too short.
       When i tried to demultiplex our above described Splitseq data with splitseqdemultiplex_0.1.1 , it was producing 23 MB of MergedCells_1.fastq file. So, i was wandering whether those reads in the  MergedCells_1.fastq were correct or not ?

Now, i understood that your software does not look for Barcodes in specific postions of Read2, which makes sense for my result.

Thank you again for this great work.
Keep it up.
with best wishes
Dipankar

**Comment by dumaatravaie** [comment] 2019-07-18 09:30
Hi Paul,
              One more thing. Even when i run splitseqdemultiplex_0.1.1 with different Round1 barcodes file ( **where the barcodes are different then the default round1 barcodes you provided** ) with the option **-1 ./testbc1.txt** ( where ./testbc1.txt is my test barcode file ) , **it always uses the default round1 barcode file  Round1_barcodes_new5.txt and produces the same results**!!!

I even used a empty round1 barcode file for testing, but splitseqdemultiplex_0.1.1 uses the default round1 barcodes and produces the same results!!!!!

      So, do you think its a bug ? Or i need to adjust the parameters?

Thank you again in advance
with best wishes
Duma

**Comment by paulranum11** [comment] 2019-07-18 11:48
Hi Duma,

Thanks again, yes this was a bug it should be fixed now.  Let me know if things work as you expect.

Thanks,
- Paul

**Comment by dumaatravaie** [comment] 2019-07-18 12:11
Hi Paul,
              Thank you a lot. It works now with different barcode file.

**There are some more things i need to ask you.**

- If i use star aligner with option **-a** then should i must use genome annotation file in GTF format with option **-y** , or this is optional ? As in your example command line there was no **-y** parameter.

- One need to use another annotation file in SAF format with the option **-s** ? Will it not work if i use a annotation file in **GTF** format ? If not, do you know any tools which can convert **GTF** to **SAF** format?

I thank you again for all your patience of replying me and making the changes in your codes.
with best wishes
Duma

**Comment by paulranum11** [comment] 2019-07-18 15:03
Hi Duma,

I just updated the syntax of the -y and -s arguments and confirmed that both work.  Please pull the latest version of of the software and use the following instructions:

1. If you use the `-a star` option then you must also provide either a `-y` (.gtf format) or `-s` (.saf format) annotation file.

2. How to choose an annotation file: If you want to assign and count reads that align to only exonic positions use -y (the GTF option).  If you want to assign and count reads that align to exonic and intronic regions use -s (the SAF option).

3. Syntax for the -y and -s commands:  You must provide "GTF" or "SAF" with the path to the annotation file. There must be a space in between the two entries as in the following example.

`-y GTF /path/to/my/.gtf`
`-s SAF /path/to/my/.saf`

NOTES: the only way to assign intronic reads is to use a .saf file.  A .saf file can be created using biomart `http://useast.ensembl.org/biomart/martview/5a9818755a5c89e3c5865cc947b3d44b` the format is as follows with NO header:
`GeneName Chromosome GeneStart GeneEnd Strand`

I hope this helps, let me know if you have further questions or issues.
Thanks,
- Paul

**Comment by dumaatravaie** [comment] 2019-07-19 07:58
Hi Paul,

                Thank you again. I will test the alignment part of **splitseqdemultiplex_0.1.1**  today and I will let you know if i find some more bugs or some other issues.

Thank you,
with best wishes,
Duma

**Comment by dumaatravaie** [comment] 2019-07-19 10:17
Hi Paul,
              Thank you a lot. I tested your **splitseqdemultiplex_0.1.1**, and i finally i was able to get it work.

There is little error when i do not use -s SAF option

splitseqdemultiplex_0.1.1.sh: line 278: [: =: unary operator expected

Also, for command line i had to use quates " " for the option after -s or -y. Otherwise it is unable to see the .saf or .gtf file, May be because its an error specific to UBUNTU ( I am using UBUNTU 18.04 ).

So, finally i used the command like this for my GTF files:

bash splitseqdemultiplex_0.1.1.sh -n 4 -e 1 -m 10 -1 Round1_barcodes_new5.txt -2 Round2_barcodes_new4.txt -3 Round3_barcodes_new4.txt -f SRR6750041_1_smalltest.fastq -r SRR6750041_2_smalltest.fastq -o results -t 20000 -g 100000 -c true -a star -x /full/file/path_of_starindex/star -y "GTF /full/file/path_of_annotation_gtf_file/genes.gtf"

Thank you again.
with best wishes
Duma

**Comment by paulranum11** [comment] 2019-07-19 13:01
Hi Duma,

Glad you have it working.  Thanks for pointing out the unary operator error.  I forgot to quote a variable in an if statement.  I fixed that and pushed another update.  Along with updates to the README indicating that the -y and -s options should be quoted.

Thanks for your help in tracking down these bugs.  I appreciate it.

- Paul

**Closed as completed** 2019-07-22 16:58 UTC
